/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWhitelist,
  IWhitelistInterface,
} from "../../interfaces/IWhitelist";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "SuccessfullyWhitelist",
    type: "event",
  },
  {
    inputs: [],
    name: "addAddressToWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): IWhitelistInterface {
    return new utils.Interface(_abi) as IWhitelistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWhitelist {
    return new Contract(address, _abi, signerOrProvider) as IWhitelist;
  }
}
