/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type VerifcaitonRecordStruct = {
  userId: PromiseOrValue<BytesLike>;
  numberTries: PromiseOrValue<BigNumberish>;
  status: PromiseOrValue<BigNumberish>;
};

export type VerifcaitonRecordStructOutput = [string, BigNumber, number] & {
  userId: string;
  numberTries: BigNumber;
  status: number;
};

export interface IFigurePrintOracleInterface extends utils.Interface {
  functions: {
    "burnUserRecord(address)": FunctionFragment;
    "createUserSimpleRecord(uint8,uint256)": FunctionFragment;
    "getChainLinkOracle()": FunctionFragment;
    "getChainLinkToken()": FunctionFragment;
    "getFee()": FunctionFragment;
    "getJobId()": FunctionFragment;
    "getLinkBalance()": FunctionFragment;
    "getUserRecord(address)": FunctionFragment;
    "getUserStatusRecord(address)": FunctionFragment;
    "getUserVerification(address)": FunctionFragment;
    "getVerifier()": FunctionFragment;
    "setChainLinkOracle(address)": FunctionFragment;
    "setChainLinkToken(address)": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "setJobId(bytes32)": FunctionFragment;
    "setVeriferRole(address)": FunctionFragment;
    "verifyFingerPrint(address,bytes,bytes)": FunctionFragment;
    "withdrawLink()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "burnUserRecord"
      | "createUserSimpleRecord"
      | "getChainLinkOracle"
      | "getChainLinkToken"
      | "getFee"
      | "getJobId"
      | "getLinkBalance"
      | "getUserRecord"
      | "getUserStatusRecord"
      | "getUserVerification"
      | "getVerifier"
      | "setChainLinkOracle"
      | "setChainLinkToken"
      | "setFee"
      | "setJobId"
      | "setVeriferRole"
      | "verifyFingerPrint"
      | "withdrawLink"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burnUserRecord",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createUserSimpleRecord",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainLinkOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainLinkToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "getJobId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLinkBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecord",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStatusRecord",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerification",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChainLinkOracle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainLinkToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setJobId",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setVeriferRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFingerPrint",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLink",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "burnUserRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createUserSimpleRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainLinkOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainLinkToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJobId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLinkBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStatusRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainLinkOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainLinkToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setJobId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVeriferRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFingerPrint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLink",
    data: BytesLike
  ): Result;

  events: {
    "FallbackCalled(address,uint256)": EventFragment;
    "ReceivedCalled(address,uint256)": EventFragment;
    "SetChainLinkOracle(address)": EventFragment;
    "SetChainLinkToken(address)": EventFragment;
    "SetFee(uint256)": EventFragment;
    "SetJobId(bytes32)": EventFragment;
    "SetVeriferRole(address)": EventFragment;
    "VerifationResponse(address,bytes32,string)": EventFragment;
    "VerifyFingerPrint(bytes,bytes32,address)": EventFragment;
    "WithDrawAmount(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FallbackCalled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedCalled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetChainLinkOracle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetChainLinkToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetJobId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetVeriferRole"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerifationResponse"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerifyFingerPrint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithDrawAmount"): EventFragment;
}

export interface FallbackCalledEventObject {
  buyer: string;
  amount: BigNumber;
}
export type FallbackCalledEvent = TypedEvent<
  [string, BigNumber],
  FallbackCalledEventObject
>;

export type FallbackCalledEventFilter = TypedEventFilter<FallbackCalledEvent>;

export interface ReceivedCalledEventObject {
  buyer: string;
  amount: BigNumber;
}
export type ReceivedCalledEvent = TypedEvent<
  [string, BigNumber],
  ReceivedCalledEventObject
>;

export type ReceivedCalledEventFilter = TypedEventFilter<ReceivedCalledEvent>;

export interface SetChainLinkOracleEventObject {
  oricle: string;
}
export type SetChainLinkOracleEvent = TypedEvent<
  [string],
  SetChainLinkOracleEventObject
>;

export type SetChainLinkOracleEventFilter =
  TypedEventFilter<SetChainLinkOracleEvent>;

export interface SetChainLinkTokenEventObject {
  linkToken: string;
}
export type SetChainLinkTokenEvent = TypedEvent<
  [string],
  SetChainLinkTokenEventObject
>;

export type SetChainLinkTokenEventFilter =
  TypedEventFilter<SetChainLinkTokenEvent>;

export interface SetFeeEventObject {
  fee: BigNumber;
}
export type SetFeeEvent = TypedEvent<[BigNumber], SetFeeEventObject>;

export type SetFeeEventFilter = TypedEventFilter<SetFeeEvent>;

export interface SetJobIdEventObject {
  jobId: string;
}
export type SetJobIdEvent = TypedEvent<[string], SetJobIdEventObject>;

export type SetJobIdEventFilter = TypedEventFilter<SetJobIdEvent>;

export interface SetVeriferRoleEventObject {
  verifer: string;
}
export type SetVeriferRoleEvent = TypedEvent<
  [string],
  SetVeriferRoleEventObject
>;

export type SetVeriferRoleEventFilter = TypedEventFilter<SetVeriferRoleEvent>;

export interface VerifationResponseEventObject {
  userAddress: string;
  requestId: string;
  isVerfied: string;
}
export type VerifationResponseEvent = TypedEvent<
  [string, string, string],
  VerifationResponseEventObject
>;

export type VerifationResponseEventFilter =
  TypedEventFilter<VerifationResponseEvent>;

export interface VerifyFingerPrintEventObject {
  userId: string;
  requestId: string;
  userAddress: string;
}
export type VerifyFingerPrintEvent = TypedEvent<
  [string, string, string],
  VerifyFingerPrintEventObject
>;

export type VerifyFingerPrintEventFilter =
  TypedEventFilter<VerifyFingerPrintEvent>;

export interface WithDrawAmountEventObject {
  buyer: string;
  amount: BigNumber;
}
export type WithDrawAmountEvent = TypedEvent<
  [string, BigNumber],
  WithDrawAmountEventObject
>;

export type WithDrawAmountEventFilter = TypedEventFilter<WithDrawAmountEvent>;

export interface IFigurePrintOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFigurePrintOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burnUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createUserSimpleRecord(
      status: PromiseOrValue<BigNumberish>,
      numberTries: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getChainLinkOracle(overrides?: CallOverrides): Promise<[string]>;

    getChainLinkToken(overrides?: CallOverrides): Promise<[string]>;

    getFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getJobId(overrides?: CallOverrides): Promise<[string]>;

    getLinkBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[VerifcaitonRecordStructOutput]>;

    getUserStatusRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getUserVerification(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getVerifier(overrides?: CallOverrides): Promise<[boolean]>;

    setChainLinkOracle(
      oricle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setChainLinkToken(
      linkToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setJobId(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setVeriferRole(
      verifer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyFingerPrint(
      userAddress: PromiseOrValue<string>,
      userId: PromiseOrValue<BytesLike>,
      fingerPrint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawLink(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  burnUserRecord(
    userAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createUserSimpleRecord(
    status: PromiseOrValue<BigNumberish>,
    numberTries: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getChainLinkOracle(overrides?: CallOverrides): Promise<string>;

  getChainLinkToken(overrides?: CallOverrides): Promise<string>;

  getFee(overrides?: CallOverrides): Promise<BigNumber>;

  getJobId(overrides?: CallOverrides): Promise<string>;

  getLinkBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getUserRecord(
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<VerifcaitonRecordStructOutput>;

  getUserStatusRecord(
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  getUserVerification(
    userAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getVerifier(overrides?: CallOverrides): Promise<boolean>;

  setChainLinkOracle(
    oricle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setChainLinkToken(
    linkToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFee(
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setJobId(
    _jobId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setVeriferRole(
    verifer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyFingerPrint(
    userAddress: PromiseOrValue<string>,
    userId: PromiseOrValue<BytesLike>,
    fingerPrint: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawLink(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burnUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createUserSimpleRecord(
      status: PromiseOrValue<BigNumberish>,
      numberTries: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getChainLinkOracle(overrides?: CallOverrides): Promise<string>;

    getChainLinkToken(overrides?: CallOverrides): Promise<string>;

    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getJobId(overrides?: CallOverrides): Promise<string>;

    getLinkBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<VerifcaitonRecordStructOutput>;

    getUserStatusRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    getUserVerification(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getVerifier(overrides?: CallOverrides): Promise<boolean>;

    setChainLinkOracle(
      oricle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setChainLinkToken(
      linkToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setJobId(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setVeriferRole(
      verifer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyFingerPrint(
      userAddress: PromiseOrValue<string>,
      userId: PromiseOrValue<BytesLike>,
      fingerPrint: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    withdrawLink(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "FallbackCalled(address,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): FallbackCalledEventFilter;
    FallbackCalled(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): FallbackCalledEventFilter;

    "ReceivedCalled(address,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): ReceivedCalledEventFilter;
    ReceivedCalled(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): ReceivedCalledEventFilter;

    "SetChainLinkOracle(address)"(
      oricle?: PromiseOrValue<string> | null
    ): SetChainLinkOracleEventFilter;
    SetChainLinkOracle(
      oricle?: PromiseOrValue<string> | null
    ): SetChainLinkOracleEventFilter;

    "SetChainLinkToken(address)"(
      linkToken?: PromiseOrValue<string> | null
    ): SetChainLinkTokenEventFilter;
    SetChainLinkToken(
      linkToken?: PromiseOrValue<string> | null
    ): SetChainLinkTokenEventFilter;

    "SetFee(uint256)"(
      fee?: PromiseOrValue<BigNumberish> | null
    ): SetFeeEventFilter;
    SetFee(fee?: PromiseOrValue<BigNumberish> | null): SetFeeEventFilter;

    "SetJobId(bytes32)"(
      jobId?: PromiseOrValue<BytesLike> | null
    ): SetJobIdEventFilter;
    SetJobId(jobId?: PromiseOrValue<BytesLike> | null): SetJobIdEventFilter;

    "SetVeriferRole(address)"(
      verifer?: PromiseOrValue<string> | null
    ): SetVeriferRoleEventFilter;
    SetVeriferRole(
      verifer?: PromiseOrValue<string> | null
    ): SetVeriferRoleEventFilter;

    "VerifationResponse(address,bytes32,string)"(
      userAddress?: PromiseOrValue<string> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      isVerfied?: PromiseOrValue<string> | null
    ): VerifationResponseEventFilter;
    VerifationResponse(
      userAddress?: PromiseOrValue<string> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      isVerfied?: PromiseOrValue<string> | null
    ): VerifationResponseEventFilter;

    "VerifyFingerPrint(bytes,bytes32,address)"(
      userId?: PromiseOrValue<BytesLike> | null,
      requestId?: null,
      userAddress?: null
    ): VerifyFingerPrintEventFilter;
    VerifyFingerPrint(
      userId?: PromiseOrValue<BytesLike> | null,
      requestId?: null,
      userAddress?: null
    ): VerifyFingerPrintEventFilter;

    "WithDrawAmount(address,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): WithDrawAmountEventFilter;
    WithDrawAmount(
      buyer?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): WithDrawAmountEventFilter;
  };

  estimateGas: {
    burnUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createUserSimpleRecord(
      status: PromiseOrValue<BigNumberish>,
      numberTries: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getChainLinkOracle(overrides?: CallOverrides): Promise<BigNumber>;

    getChainLinkToken(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getJobId(overrides?: CallOverrides): Promise<BigNumber>;

    getLinkBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserStatusRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserVerification(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    setChainLinkOracle(
      oricle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setChainLinkToken(
      linkToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setJobId(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setVeriferRole(
      verifer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyFingerPrint(
      userAddress: PromiseOrValue<string>,
      userId: PromiseOrValue<BytesLike>,
      fingerPrint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawLink(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createUserSimpleRecord(
      status: PromiseOrValue<BigNumberish>,
      numberTries: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getChainLinkOracle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainLinkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getJobId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLinkBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserStatusRecord(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserVerification(
      userAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setChainLinkOracle(
      oricle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setChainLinkToken(
      linkToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setJobId(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setVeriferRole(
      verifer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyFingerPrint(
      userAddress: PromiseOrValue<string>,
      userId: PromiseOrValue<BytesLike>,
      fingerPrint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawLink(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
