/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iExchangeSol from "./IExchange.sol";
export type { iExchangeSol };
export type { ILock } from "./ILock";
export type { IMarketplace } from "./IMarketplace";
export type { ITKDev } from "./ITKDev";
export type { ITKDevDAO } from "./ITKDevDAO";
export type { IToken } from "./IToken";
export type { IWhitelist } from "./IWhitelist";
