/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exchangeSol from "./Exchange.sol";
export type { exchangeSol };
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as tkdaoSol from "./TKDAO.sol";
export type { tkdaoSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { Lock } from "./Lock";
export type { TKDevs } from "./TKDevs";
export type { Whitelist } from "./Whitelist";
