/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as orcaleUrlProviderProxySol from "./OrcaleUrlProviderProxy.sol";
export type { orcaleUrlProviderProxySol };
