/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOrcaleUrlProvider,
  IOrcaleUrlProviderInterface,
} from "../../../contracts/interfaces/IOrcaleUrlProvider";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "url",
        type: "string",
      },
    ],
    name: "UrlChange",
    type: "event",
  },
  {
    inputs: [],
    name: "getURL",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "url",
        type: "string",
      },
    ],
    name: "setUrl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOrcaleUrlProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IOrcaleUrlProviderInterface {
    return new utils.Interface(_abi) as IOrcaleUrlProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOrcaleUrlProvider {
    return new Contract(address, _abi, signerOrProvider) as IOrcaleUrlProvider;
  }
}
